export const nodes = [
// Main categories
{ id: "Everything" },
{ id: "Internet" },
{ id: "Science" },
{ id: "Technology" },
{ id: "Places" },
{ id: "Entertainment" },
{ id: "Culture" },
{ id: "Companies" },

// Internet
{ id: "Websites" },
{ id: "Apps" },
{ id: "Social Media" },
{ id: "E-commerce" },
{ id: "Search Engines" },
{ id: "Email" },

// Apps
{ id: "Mobile Apps" },
{ id: "Desktop Apps" },
{ id: "iOS Apps" },
{ id: "Android Apps" },
{ id: "Productivity Apps" },
{ id: "Finance Apps" },
{ id: "Gaming Apps" },

// Social Media / Companies / Bridges
{ id: "Instagram" },
{ id: "Facebook" },
{ id: "WhatsApp" },
{ id: "Twitter" },
{ id: "LinkedIn" },
{ id: "TikTok" },
{ id: "Snapchat" },
{ id: "YouTube" },
{ id: "Pinterest" },
{ id: "Reddit" },
{ id: "Meta" },
{ id: "Google" },
{ id: "Apple" },
{ id: "Microsoft" },
{ id: "ByteDance" },
{ id: "Snap Inc" },
{ id: "Pinterest Inc" },

// E-commerce
{ id: "Amazon" },
{ id: "eBay" },
{ id: "Alibaba" },
{ id: "Flipkart" },
{ id: "Etsy" },
{ id: "AWS" },

// Science topics
{ id: "Physics" },
{ id: "Chemistry" },
{ id: "Biology" },
{ id: "Astronomy" },
{ id: "Quantum Mechanics" },
{ id: "Relativity" },
{ id: "Thermodynamics" },
{ id: "Particle Physics" },
{ id: "Genetics" },
{ id: "Ecology" },
{ id: "Microbiology" },
{ id: "Botany" },
{ id: "Zoology" },
{ id: "Black Holes" },
{ id: "Time Dilation" },
{ id: "DNA" },
{ id: "RNA" },
{ id: "CRISPR" },
{ id: "Gene Therapy" },
{ id: "Climate Change" },
{ id: "Biodiversity" },
{ id: "Evolution" },

// Science concepts referenced in edges
{ id: "Radioactivity" },
{ id: "Photoelectric Effect" },
{ id: "Gravity" },
{ id: "Calculus" },
{ id: "Modern Physics" },
{ id: "Natural Selection" },
{ id: "Atomic Structure" },
{ id: "Nuclear Physics" },
{ id: "Nuclear Reactor" },
{ id: "DNA Structure" },
{ id: "DNA Double Helix" },
{ id: "Germ Theory" },
{ id: "Vaccination" },
{ id: "Piezoelectricity" },

// Scientists
{ id: "Marie Curie" },
{ id: "Pierre Curie" },
{ id: "Albert Einstein" },
{ id: "Isaac Newton" },
{ id: "Galileo Galilei" },
{ id: "Charles Darwin" },
{ id: "Gregor Mendel" },
{ id: "Dmitri Mendeleev" },
{ id: "Niels Bohr" },
{ id: "Ernest Rutherford" },
{ id: "Enrico Fermi" },
{ id: "Rosalind Franklin" },
{ id: "James Watson" },
{ id: "Francis Crick" },
{ id: "Louis Pasteur" },

// Countries
{ id: "Germany" },
{ id: "France" },
{ id: "England" },
{ id: "Italy" },
{ id: "Austria" },
{ id: "Russia" },
{ id: "Denmark" },
{ id: "New Zealand" },
{ id: "Poland" },
{ id: "USA" },

// Continents / regions
{ id: "Europe" },

// Periodic Table
{ id: "Periodic Table" },
{ id: "Hydrogen" },
{ id: "Helium" },
{ id: "Lithium" },
{ id: "Beryllium" },
{ id: "Boron" },
{ id: "Carbon" },
{ id: "Nitrogen" },
{ id: "Oxygen" },
{ id: "Fluorine" },
{ id: "Neon" },
{ id: "Sodium" },
{ id: "Magnesium" },
{ id: "Aluminum" },
{ id: "Silicon" },
{ id: "Phosphorus" },
{ id: "Sulfur" },
{ id: "Chlorine" },
{ id: "Argon" },
{ id: "Potassium" },
{ id: "Calcium" },
{ id: "Scandium" },
{ id: "Titanium" },
{ id: "Vanadium" },
{ id: "Chromium" },
{ id: "Manganese" },
{ id: "Iron" },
{ id: "Cobalt" },
{ id: "Nickel" },
{ id: "Copper" },
{ id: "Zinc" },
{ id: "Gallium" },
{ id: "Germanium" },
{ id: "Arsenic" },
{ id: "Selenium" },
{ id: "Bromine" },
{ id: "Krypton" },
{ id: "Rubidium" },
{ id: "Strontium" },
{ id: "Yttrium" },
{ id: "Zirconium" },
{ id: "Niobium" },
{ id: "Molybdenum" },
{ id: "Technetium" },
{ id: "Ruthenium" },
{ id: "Rhodium" },
{ id: "Palladium" },
{ id: "Silver" },
{ id: "Cadmium" },
{ id: "Indium" },
{ id: "Tin" },
{ id: "Antimony" },
{ id: "Tellurium" },
{ id: "Iodine" },
{ id: "Xenon" },
{ id: "Cesium" },
{ id: "Barium" },
{ id: "Lanthanum" },
{ id: "Cerium" },
{ id: "Praseodymium" },
{ id: "Neodymium" },
{ id: "Promethium" },
{ id: "Samarium" },
{ id: "Europium" },
{ id: "Gadolinium" },
{ id: "Terbium" },
{ id: "Dysprosium" },
{ id: "Holmium" },
{ id: "Erbium" },
{ id: "Thulium" },
{ id: "Ytterbium" },
{ id: "Lutetium" },
{ id: "Hafnium" },
{ id: "Tantalum" },
{ id: "Tungsten" },
{ id: "Rhenium" },
{ id: "Osmium" },
{ id: "Iridium" },
{ id: "Platinum" },
{ id: "Gold" },
{ id: "Mercury" },
{ id: "Thallium" },
{ id: "Lead" },
{ id: "Bismuth" },
{ id: "Polonium" },
{ id: "Astatine" },
{ id: "Radon" },
{ id: "Francium" },
{ id: "Radium" },
{ id: "Actinium" },
{ id: "Thorium" },
{ id: "Protactinium" },
{ id: "Uranium" },
{ id: "Neptunium" },
{ id: "Plutonium" },
{ id: "Americium" },
{ id: "Curium" },
{ id: "Berkelium" },
{ id: "Californium" },
{ id: "Einsteinium" },
{ id: "Fermium" },
{ id: "Mendelevium" },
{ id: "Nobelium" },
{ id: "Lawrencium" },
{ id: "Rutherfordium" },
{ id: "Dubnium" },
{ id: "Seaborgium" },
{ id: "Bohrium" },
{ id: "Hassium" },
{ id: "Meitnerium" },
{ id: "Darmstadtium" },
{ id: "Roentgenium" },
{ id: "Copernicium" },
{ id: "Nihonium" },
{ id: "Flerovium" },
{ id: "Moscovium" },
{ id: "Livermorium" },
{ id: "Tennessine" },
{ id: "Oganesson" },

// Technology
{ id: "Programming Languages" },
{ id: "Python" },
{ id: "JavaScript" },
{ id: "Java" },
{ id: "C++" },
{ id: "React" },
{ id: "Node.js" },
{ id: "Databases" },
{ id: "SQL" },
{ id: "NoSQL" },
{ id: "MongoDB" },
{ id: "PostgreSQL" },
{ id: "Firebase" },
{ id: "AI" },
{ id: "Machine Learning" },
{ id: "Deep Learning" },
{ id: "Neural Networks" },
{ id: "Robotics" },
{ id: "Cloud Computing" },
{ id: "Cybersecurity" },
{ id: "Blockchain" },
{ id: "IoT" },
{ id: "HTML" },
{ id: "CSS" },

// Birth and Death
{ id: "Birth" },
{ id: "Death" },
{ id: "Years" },

// Years
...Array.from({ length: 527 }, (_, i) => ({ id: (1500 + i).toString() })) // 1500 to 2026
];




export const edges = [

// Years
...Array.from({ length: 527 }, (_, i) => {
    const year = (1500 + i).toString();
    return { source: "Years", target: year };
}),

//Birth
{ source: "1867", target: "Birth" },
//Death
{ source: "1934", target: "Death" },
{ source: "1906", target: "Death" },

// Main categories
{ source: "Everything", target: "Internet" },
{ source: "Everything", target: "Science" },
{ source: "Everything", target: "Technology" },
{ source: "Everything", target: "Places" },
{ source: "Everything", target: "Entertainment" },
{ source: "Everything", target: "Culture" },
{ source: "Everything", target: "Companies" },

// Internet hierarchy
{ source: "Internet", target: "Websites" },
{ source: "Internet", target: "Apps" },
{ source: "Internet", target: "Search Engines" },
{ source: "Internet", target: "Social Media" },
{ source: "Internet", target: "E-commerce" },
{ source: "Internet", target: "Email" },
{ source: "Internet", target: "Reddit"},

// Apps
{ source: "Apps", target: "Mobile Apps" },
{ source: "Apps", target: "Desktop Apps" },
{ source: "Apps", target: "iOS Apps" },
{ source: "Apps", target: "Android Apps" },
{ source: "Apps", target: "Productivity Apps" },
{ source: "Apps", target: "Finance Apps" },
{ source: "Apps", target: "Gaming Apps" },
{ source: "Mobile Apps", target: "iOS Apps" },
{ source: "Mobile Apps", target: "Android Apps" },

// Websites
{ source: "Websites", target: "Social Media" },
{ source: "Websites", target: "E-commerce" },

// Social Media
{ source: "Social Media", target: "Instagram" },
{ source: "Social Media", target: "Facebook" },
{ source: "Social Media", target: "WhatsApp" },
{ source: "Social Media", target: "Twitter" },
{ source: "Social Media", target: "LinkedIn" },
{ source: "Social Media", target: "TikTok" },
{ source: "Social Media", target: "Snapchat" },
{ source: "Social Media", target: "YouTube" },
{ source: "Social Media", target: "Pinterest" },

// Social Media bridges
{ source: "Instagram", target: "iOS Apps" },
{ source: "Instagram", target: "Android Apps" },
{ source: "Instagram", target: "Meta" },
{ source: "Facebook", target: "iOS Apps" },
{ source: "Facebook", target: "Android Apps" },
{ source: "Facebook", target: "Meta" },
{ source: "WhatsApp", target: "iOS Apps" },
{ source: "WhatsApp", target: "Android Apps" },
{ source: "WhatsApp", target: "Meta" },
{ source: "Twitter", target: "Meta" },
{ source: "Twitter", target: "Websites" },
{ source: "Twitter", target: "Companies" },
{ source: "LinkedIn", target: "Microsoft" },
{ source: "TikTok", target: "ByteDance" },
{ source: "Snapchat", target: "Snap Inc" },
{ source: "Pinterest", target: "Pinterest Inc" },
{ source: "YouTube", target: "Google" },
{ source: "Apple", target: "iOS Apps" },
{ source: "Google", target: "Android Apps" },

// E-commerce
{ source: "E-commerce", target: "Amazon" },
{ source: "Amazon", target: "AWS" },
{ source: "E-commerce", target: "eBay" },
{ source: "E-commerce", target: "Alibaba" },
{ source: "E-commerce", target: "Flipkart" },
{ source: "E-commerce", target: "Etsy" },

// Science topics
{ source: "Science", target: "Physics" },
{ source: "Science", target: "Chemistry" },
{ source: "Science", target: "Biology" },
{ source: "Science", target: "Astronomy" },
{ source: "Physics", target: "Quantum Mechanics" },
{ source: "Physics", target: "Relativity" },
{ source: "Physics", target: "Thermodynamics" },
{ source: "Quantum Mechanics", target: "Particle Physics" },
{ source: "Quantum Mechanics", target: "AI" },
{ source: "Relativity", target: "Black Holes" },
{ source: "Relativity", target: "Thermodynamics" },
{ source: "Relativity", target: "Time Dilation" },
{ source: "Biology", target: "Ecology" },
{ source: "Biology", target: "Microbiology" },
{ source: "Biology", target: "Botany" },
{ source: "Biology", target: "Zoology" },
{ source: "Biology", target: "Genetics" },
{ source: "Ecology", target: "Climate Change" },
{ source: "Ecology", target: "Biodiversity" },
{ source: "Ecology", target: "Evolution" },
{ source: "Microbiology", target: "DNA" },
{ source: "Microbiology", target: "RNA" },
{ source: "Microbiology", target: "CRISPR" },
{ source: "Microbiology", target: "Gene Therapy" },

// Scientists
{ source: "Marie Curie", target: "Poland" },
{ source: "Marie Curie", target: "Polonium" },
{ source: "Marie Curie", target: "Radium" },
{ source: "Marie Curie", target: "Radioactivity" },
{ source: "Marie Curie", target: "1867" },
{ source: "Marie Curie", target: "1934" },

{ source: "Pierre Curie", target: "France" },
{ source: "Pierre Curie", target: "Piezoelectricity" },
{ source: "Pierre Curie", target: "Curium" },
{ source: "Pierre Curie", target: "1859" },
{ source: "Pierre Curie", target: "1906" },

{ source: "Albert Einstein", target: "Germany" },
{ source: "Albert Einstein", target: "Relativity" },
{ source: "Albert Einstein", target: "Photoelectric Effect" },
{ source: "Albert Einstein", target: "Einsteinium" },
{ source: "Albert Einstein", target: "1879" },
{ source: "Albert Einstein", target: "1955" },

{ source: "Isaac Newton", target: "England" },
{ source: "Isaac Newton", target: "Gravity" },
{ source: "Isaac Newton", target: "Calculus" },
{ source: "Isaac Newton", target: "1643" },
{ source: "Isaac Newton", target: "1727" },

{ source: "Galileo Galilei", target: "Italy" },
{ source: "Galileo Galilei", target: "Astronomy" },
{ source: "Galileo Galilei", target: "Modern Physics" },
{ source: "Galileo Galilei", target: "1564" },
{ source: "Galileo Galilei", target: "1642" },

{ source: "Charles Darwin", target: "England" },
{ source: "Charles Darwin", target: "Evolution" },
{ source: "Charles Darwin", target: "Natural Selection" },
{ source: "Charles Darwin", target: "1809" },
{ source: "Charles Darwin", target: "1882" },

{ source: "Gregor Mendel", target: "Austria" },
{ source: "Gregor Mendel", target: "Genetics" },
{ source: "Gregor Mendel", target: "1822" },
{ source: "Gregor Mendel", target: "1884" },

{ source: "Dmitri Mendeleev", target: "Russia" },
{ source: "Dmitri Mendeleev", target: "Periodic Table" },
{ source: "Dmitri Mendeleev", target: "Mendelevium" },
{ source: "Dmitri Mendeleev", target: "1834" },
{ source: "Dmitri Mendeleev", target: "1907" },

{ source: "Niels Bohr", target: "Denmark" },
{ source: "Niels Bohr", target: "Atomic Structure" },
{ source: "Niels Bohr", target: "Bohrium" },
{ source: "Niels Bohr", target: "1885" },
{ source: "Niels Bohr", target: "1962" },

{ source: "Ernest Rutherford", target: "New Zealand" },
{ source: "Ernest Rutherford", target: "Nuclear Physics" },
{ source: "Ernest Rutherford", target: "Rutherfordium" },
{ source: "Ernest Rutherford", target: "1871" },
{ source: "Ernest Rutherford", target: "1937" },

{ source: "Enrico Fermi", target: "Italy" },
{ source: "Enrico Fermi", target: "Nuclear Reactor" },
{ source: "Enrico Fermi", target: "Fermium" },
{ source: "Enrico Fermi", target: "1901" },
{ source: "Enrico Fermi", target: "1954" },

{ source: "Rosalind Franklin", target: "England" },
{ source: "Rosalind Franklin", target: "DNA Structure" },
{ source: "Rosalind Franklin", target: "1920" },
{ source: "Rosalind Franklin", target: "1958" },

{ source: "James Watson", target: "USA" },
{ source: "James Watson", target: "DNA Double Helix" },
{ source: "James Watson", target: "1928" },

{ source: "Francis Crick", target: "England" },
{ source: "Francis Crick", target: "DNA Double Helix" },
{ source: "Francis Crick", target: "1916" },
{ source: "Francis Crick", target: "2004" },

{ source: "Louis Pasteur", target: "France" },
{ source: "Louis Pasteur", target: "Germ Theory" },
{ source: "Louis Pasteur", target: "Vaccination" },
{ source: "Louis Pasteur", target: "1822" },
{ source: "Louis Pasteur", target: "1895" },

// Periodic Table
...Array.from({ length: 118 }, (_, i) => {
const elements = [
    "Hydrogen","Helium","Lithium","Beryllium","Boron","Carbon","Nitrogen","Oxygen",
    "Fluorine","Neon","Sodium","Magnesium","Aluminum","Silicon","Phosphorus","Sulfur",
    "Chlorine","Argon","Potassium","Calcium","Scandium","Titanium","Vanadium","Chromium",
    "Manganese","Iron","Cobalt","Nickel","Copper","Zinc","Gallium","Germanium","Arsenic",
    "Selenium","Bromine","Krypton","Rubidium","Strontium","Yttrium","Zirconium","Niobium",
    "Molybdenum","Technetium","Ruthenium","Rhodium","Palladium","Silver","Cadmium","Indium",
    "Tin","Antimony","Tellurium","Iodine","Xenon","Cesium","Barium","Lanthanum","Cerium",
    "Praseodymium","Neodymium","Promethium","Samarium","Europium","Gadolinium","Terbium",
    "Dysprosium","Holmium","Erbium","Thulium","Ytterbium","Lutetium","Hafnium","Tantalum",
    "Tungsten","Rhenium","Osmium","Iridium","Platinum","Gold","Mercury","Thallium","Lead",
    "Bismuth","Polonium","Astatine","Radon","Francium","Radium","Actinium","Thorium",
    "Protactinium","Uranium","Neptunium","Plutonium","Americium","Curium","Berkelium",
    "Californium","Einsteinium","Fermium","Mendelevium","Nobelium","Lawrencium",
    "Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium",
    "Roentgenium","Copernicium","Nihonium","Flerovium","Moscovium","Livermorium",
    "Tennessine","Oganesson"
];
return { source: "Periodic Table", target: elements[i] };
}),

// Technology
{ source: "Technology", target: "Programming Languages" },
{ source: "Technology", target: "Databases" },
{ source: "Technology", target: "AI" },
{ source: "Technology", target: "Machine Learning" },
{ source: "Technology", target: "Deep Learning" },
{ source: "Technology", target: "Neural Networks" },
{ source: "Technology", target: "Robotics" },
{ source: "Technology", target: "Cloud Computing" },
{ source: "Technology", target: "Cybersecurity" },
{ source: "Technology", target: "Blockchain" },
{ source: "Technology", target: "IoT" },
{ source: "Technology", target: "HTML" },
{ source: "Technology", target: "CSS" },

// Programming bridges
{ source: "Programming Languages", target: "Python" },
{ source: "Programming Languages", target: "JavaScript" },
{ source: "Programming Languages", target: "Java" },
{ source: "Programming Languages", target: "C++" },
{ source: "Python", target: "Machine Learning" },
{ source: "Machine Learning", target: "AI" },
{ source: "AI", target: "Deep Learning" },
{ source: "Deep Learning", target: "Neural Networks" },
{ source: "JavaScript", target: "React" },
{ source: "JavaScript", target: "Node.js" },
{ source: "Databases", target: "SQL" },
{ source: "Databases", target: "NoSQL" },
{ source: "SQL", target: "PostgreSQL" },
{ source: "NoSQL", target: "MongoDB" },
{ source: "Databases", target: "Firebase" },
{ source: "HTML", target: "CSS" },
{ source: "HTML", target: "Websites" },
{ source: "CSS", target: "Websites" },
{ source: "HTML", target: "JavaScript" },

// Places / Continents
{ source: "Europe", target: "Poland" }
];
